---
title: "It's time!"
description: |
  The omniprescence of glyphosate.
author:
  - name: Misson Charlotte
    url: {}
date: 10-16-2019
bibliography: "biblio/glyphosate.bib"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## Context  
Some people in Herault (France) did analyse their urine, searching for an extreamly dangerous herbicid called "glyphosate".  
*What atre the results of analysis?*  
**Every sample were positives for glyphosate!** The only difference is samples is the rate of the molecule.  
  
However the profile of people who did that test is far from the results. For exemple [@ortegaCentainesPisseursVolontaires2019], Gregory who's living as healthy as possible:  
- He eats only biological products (except meat),  
- He practices sport several hours a week,  
Despite this, the analysis of Gregory reveals that the rate of glyphosate is more than three times higher than the authorized dose!  

Angry at this results, 44 persons have filed a complaint at the republic persecutor of Montpellier. They are really upset against the politicians who accepted to renew the authorisation of salling and using that poison.   

## Glyphosate study

The possible consequences on animal health (including humans) is a huge debate in the world. This present article shows the results of studiing glyphosate's on exposed rats at the "safe rate".  


### Method

- The samples were pregnants rats.  
- The stage of pregnancy is important : the study starts at day 6 of gestation. 
- The rate of glyphosate used is the "safe dose" : 1.75mg/kg/day.  

Pregnant rats were exposed to glyphosate by drinking water. Rats consommed the water from day 6 of gestation, to postanal day 120.  
Then, two groups were formed randomly :  
- Group 1 : the rats were sacrified after puberty.  
- Group 2 : the rats were sacrified at adulthood.

### Conclusion

For US, the **safe rate** of herbicids contening glyphosate is **1.75mg/kg/day**. Apart from this average, scientists have prouved that a rate lower than the "safe rate" may have healthy consequences on a rat population. More precisealy, the problems are for reproduction and developpement.  


## Glossary
- gestational day  
- weaning = sevrage  
- offspring = progéniture  
- assessed = évalué  
- landmarks = repères  
- pups = bébés rats  
- adulthood = âge adulte

## Bibliography 

